name: Stellar Project CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  web-app:
    name: Build & Test Web Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Frontend Tests
        run: npm run test

      - name: Build Web Application
        run: npm run build
        env:
          CI: false

  smart-contract:
    name: Test Soroban Smart Contracts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "TranscendenceContract -> target"

      - name: Run Contract Tests
        run: cargo test
        working-directory: TranscendenceContract
